### ISSUE TITLE
Связь пункта правил и статей КоАП / УК РФ?

### ISSUE THREAD

**Issue by etspring** [etspring/pdd_russia#11]
**Нужно ли?**
С моей точки зрения оно нужно.
Напоминание о наказании способствует соблюдению.

**Comment by nikita-komissarov** [comment]
Да, хорошая идея

**Comment by etspring** [comment]
> Да, хорошая идея

Пока не нашел вменяемого способа связать всё это. Основная проблема - отмена/возобновление действия пунктов КоАП.

**Comment by nikita-komissarov** [comment]
Давай порассуждаем, может быть найдется решение.

Для начала — откуда ты планируешь брать сам список статей КоАП?
