### ISSUE TITLE
Отсутствуют картинки

### ISSUE THREAD

**Issue by canis** [etspring/pdd_russia#12]
(t = билет, q = вопрос)

```
./images/A_B/1871b903ddd6b18d2bc45133234dd7fa.jpg (t02 q01)
./images/A_B/3967ea92f049121b27547528fd472093.jpg (t04 q09)
./images/A_B/456767f8b2e0d39f83d8f9f1b2a378da.jpg (t05 q12)
./images/A_B/e5c4d4989ef9427567d3944a43de239c.jpg (t08 q08)
./images/A_B/c149e9f2ca6afaf456691db1d9126d64.jpg (t09 q13)
./images/A_B/dd7e958840da9ddd1c102a65d8d5c03f.jpg (t09 q15)
./images/A_B/74b185800c36d3b6228f4bc0dfbad844.jpg (t38 q01)

./images/C_D/fcd94e9c6f1cd1bbc189f8821f9ea5a1.jpg (t02 q01)
./images/C_D/69b062b40d4304b1244110310a6aaea8.jpg (t04 q09)
./images/C_D/63fee62f3d0f743c2f48f714db5fd3fe.jpg (t08 q08)
./images/C_D/e2df8420edfff761f06e9f0b2c4c2df2.jpg (t09 q13)
./images/C_D/9f82b084b60ba5ea0e5f0580e7b006e9.jpg (t09 q15)
./images/C_D/07f8422f9127d04cf1bdc5f50eb0d009.jpg (t38 q01)
```

**Comment by canis** [comment]
Извиняюсь, скрипт лажанул.

**Comment by canis** [comment]
Хотя нет. Проблема есть.

Итак, имеются пары вопросов, имеющие разные (на самом деле) картинки, но одинаковый набор ответов, в т.ч. одинаковый правильный ответ. При этом у вопросов одинаковый id!

(здесь и далее: `t39q19` = билет 39, вопрос 19)

AB:
- `t01q15` и `t09q15`, id: `c64eefab25596af3056aa4b69e92516e`
- `t04q09` и `t30q02`, id: `5ccc967d70f19d41f276ce69b2ad1334`
- `t05q12` и `t24q12`, id: `592c5535461a8d7a15d496c3d5862a0e`
- `t07q14` и `t09q13`, id: `059bf18cc5917313c7c2e73e20d41726` (картинки почти одинаковые)
- `t08q08` и `t10q08`, id: `76c1351bb5fb6e68489cabe11aa628ec`
- `t23q01` и `t38q01`, id: `d6378c5bddd1d7d45347aaef5c39b75c`

----

CD:
- `t01q15` и `t09q15`, id: `c64eefab25596af3056aa4b69e92516e`
- `t04q09` и `t30q02`, id: `5ccc967d70f19d41f276ce69b2ad1334`
- `t07q14` и `t09q13`, id: `3a327387b31e1b6a357d164227ed31e0` (картинки почти одинаковые)
- `t08q08` и `t10q08`, id: `76c1351bb5fb6e68489cabe11aa628ec`
- `t23q01` и `t38q01`, id: `21e54fddd1ab30f78f4db2b1261e32e6`

----

При этом, есть одна пара билетов и в AB, и в CD, которая действительно использует одну и ту же картинку в разных вопросах (с разным набором ответов, разумеется). Это `t02q01` и `t19q02`. Больше таких случаев не выявлено.

**Comment by etspring** [comment]
Будет исправлено в ближайшем обновлении ( думаю, на этой неделе катну ).
