### ISSUE TITLE
Улучшение графических материалов в части дорожных знаков

### ISSUE THREAD

**Issue by etspring** [etspring/pdd_russia#16]
Сейчас граф.материалы предаставлены форматами gif/jpeg.
Хочется перейти на svg.

**Comment by zkelo** [comment]
> Хочется перейти на svg.

Или на `webp`, как вариант

**Comment by etspring** [comment]
> > Хочется перейти на svg.
> 
> Или на `webp`, как вариант

Насколько я помню  - с отображением webp на ios были некоторые трудности.
